apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ollq7b26j-nodejs
  janus-idp.io/tekton: ollq7b26j-nodejs
  backstage.io/kubernetes-id: ollq7b26j-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ollq7b26j-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
